import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/app/globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import NavBar from "@/components/NavBar";
import Footer from "@/components/ui/footer";
import { Toaster } from "sonner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col flex-1 min-h-screen`}>
      <NavBar />
        <AuthProvider>
          <div className="flex-1 pt-25 [&>*:first-child[data-homepage]]:!-mt-25">{children}</div>
          <Toaster position="top-center" richColors />
        </AuthProvider>
        <Footer></Footer>
        
        
      </body>
    </html>
  );
}
